### PR TITLE
Parallelism

### PR DESCRIPTION
**Pull request by ypawar159**
Hi,
I have used concurrent futures for parallel processing the xml to json conversion.

### CODE REVIEW

**Comment by researchgraphsafe** [comment]
@ypawar159 This patch worked very well. May I ask how did you find this code? and what encouraged your contribution to this code-base?

**Comment by ypawar159** [comment]
I read it in project description on freelancer while searching for a small project.
My freelancer profile:
https://www.freelancer.in/u/yogeshpawar159

I was working on it but by the time I tried to bid after completion of the code it was already given to someone else. As I had the code ready and didn't see anyone forked from repo yet I submitted the PR.
:)

**Comment by ypawar159** [comment]
@researchgraphsafe you can contact me on freelancer for any other python related projects like web scraping, AWS, desktop apps etc.

**Comment by researchgraphsafe** [comment]
@ypawar159, Sure, please send me an email to amir[dot]aryani{a-t}researchgraph[dot]org

**Pull request merged**
